"""platform_app.frontend_routes.auth —— AUTH 补充路由(/api/auth/*)。

原单文件「AUTH supplements」段逐端点搬运,零行为变化:
改密 / 登录历史(?format=csv)/ 会话列表 / 单会话吊销 / 吊销全部其它会话。
"""
from __future__ import annotations

import csv
import io

from fastapi import Request
from fastapi.responses import StreamingResponse

from .. import auth as _auth
from ..api import SESSION_COOKIE, json_response, require_user
from ..db import connect, init_db, limit_value
from ..security import hash_password, verify_password
from ._shared import _bad, router


# ------------------------------------------------------------
#  AUTH supplements
# ------------------------------------------------------------
@router.post("/api/auth/password")
async def api_change_password(request: Request):
    """Change current user's password (`current` -> `next`)."""
    user = require_user(request)
    body = await request.json()
    cur_pw = body.get("current") or ""
    next_pw = body.get("next") or ""
    if len(next_pw) < _auth.MIN_PASSWORD_LENGTH:
        return _bad(f"新密码至少 {_auth.MIN_PASSWORD_LENGTH} 位")
    init_db()
    with connect() as db:
        row = db.execute("select password_hash from users where id = %s", (user["id"],)).fetchone()
        if not row:
            return _bad("用户不存在", status=404)
        has_existing_password = bool(row["password_hash"])
        if has_existing_password and not verify_password(cur_pw, row["password_hash"]):
            return _bad("当前密码错误")
        db.execute(
            "update users set password_hash = %s, row_version = row_version + 1, updated_at = now() where id = %s",
            (hash_password(next_pw), user["id"]),
        )
        # Optional: revoke all OTHER sessions (keep current cookie).
        # 用 token_hash 而非明文 token — 新会话 token=''，旧查法对新会话全部静默失效。
        token = request.cookies.get(SESSION_COOKIE)
        if token:
            from ..auth import _hash_token
            db.execute(
                "delete from sessions where user_id = %s and token_hash <> %s",
                (user["id"], _hash_token(token)),
            )
    return json_response({"ok": True, "message": "密码已修改" if has_existing_password else "密码已设置"})


@router.get("/api/auth/login-history")
async def api_login_history(request: Request):
    """Return last N login_audit rows for the current user. ?format=csv supported."""
    user = require_user(request)
    init_db()
    fmt = (request.query_params.get("format") or "").lower()
    limit = limit_value(request.query_params.get("limit"), default=50, maximum=500)
    with connect() as db:
        db.execute(
            """
            create table if not exists login_audit (
              id bigint generated by default as identity primary key,
              username text, ip text, event text not null,
              meta jsonb not null default '{}'::jsonb,
              created_at timestamptz not null default now()
            )
            """
        )
        rows = db.execute(
            """
            select id, username, ip, event, meta, created_at
            from login_audit
            where username = %s
            order by created_at desc
            limit %s
            """,
            (user.get("username"), limit),
        ).fetchall()
    items = [
        {
            "id": r["id"],
            "at": r["created_at"].isoformat() if r["created_at"] else None,
            "ip": r["ip"],
            "user_agent": (r["meta"] or {}).get("ua") if isinstance(r["meta"], dict) else None,
            "result": "ok" if r["event"] == "login_ok" else "blocked",
            "event": r["event"],
        }
        for r in rows
    ]
    if fmt == "csv":
        buf = io.StringIO()
        w = csv.writer(buf)
        w.writerow(["at", "ip", "event", "result"])
        for i in items:
            w.writerow([i.get("at"), i.get("ip"), i.get("event"), i.get("result")])
        return StreamingResponse(
            io.BytesIO(buf.getvalue().encode("utf-8")),
            media_type="text/csv; charset=utf-8",
            headers={"Content-Disposition": 'attachment; filename="login-history.csv"'},
        )
    return json_response({"ok": True, "entries": items})


@router.get("/api/auth/sessions")
async def api_list_sessions(request: Request):
    user = require_user(request)
    init_db()
    from ..auth import _hash_token
    cur_token = request.cookies.get(SESSION_COOKIE) or ""
    cur_hash = _hash_token(cur_token) if cur_token else ""
    with connect() as db:
        rows = db.execute(
            """
            select token_hash, user_id, created_at, expires_at
            from sessions
            where user_id = %s and expires_at > now()
            order by created_at desc
            """,
            (user["id"],),
        ).fetchall()
    out = []
    for r in rows:
        thash = r["token_hash"] or ""
        # P1-2 方案B: 使用前 24 位作为可见 session ID（96 bit，碰撞概率极低），替代原 12 位
        display_id = thash[:24] if thash else ""
        out.append({
            "id": display_id,
            "session_id": display_id,
            "created_at": r["created_at"].isoformat() if r["created_at"] else None,
            "expires_at": r["expires_at"].isoformat() if r["expires_at"] else None,
            "last_seen_at": r["created_at"].isoformat() if r["created_at"] else None,
            "current": bool(cur_hash) and thash == cur_hash,
        })
    return json_response({"ok": True, "sessions": out})


@router.post("/api/auth/sessions/revoke")
async def api_revoke_session(request: Request):
    user = require_user(request)
    body = await request.json()
    sid = body.get("session_id") or body.get("id") or ""
    if not sid:
        return _bad("缺少 session_id")
    init_db()
    from ..auth import _hash_token
    cur_token = request.cookies.get(SESSION_COOKIE) or ""
    cur_hash = _hash_token(cur_token) if cur_token else ""
    # P1-2 方案B: sid 已是前 24 位前缀，用 startswith 精确前缀匹配代替后缀 LIKE 碰撞
    if len(sid) != 24 or not all(c in "0123456789abcdef" for c in sid):
        return _bad("无效的 session_id 格式")
    with connect() as db:
        # 用 token_hash 前 24 位前缀精确匹配；当前会话不能被自我吊销
        deleted = db.execute(
            "delete from sessions where user_id = %s and left(token_hash, 24) = %s and token_hash <> %s returning token_hash",
            (user["id"], sid, cur_hash),
        ).fetchone()
    return json_response({"ok": True, "deleted": bool(deleted)})


@router.post("/api/auth/sessions/revoke-all")
async def api_revoke_all_sessions(request: Request):
    user = require_user(request)
    init_db()
    from ..auth import _hash_token
    cur_token = request.cookies.get(SESSION_COOKIE) or ""
    cur_hash = _hash_token(cur_token) if cur_token else ""
    with connect() as db:
        n = db.execute(
            "delete from sessions where user_id = %s and token_hash <> %s",
            (user["id"], cur_hash),
        ).statusmessage
    return json_response({"ok": True, "result": n})
